// Generated by CoffeeScript 2.5.0
(function() {
  //!/usr/bin/env coffee
  var fs, klawSync, log, path, src;

  klawSync = require('klaw-sync');

  fs = require('fs');

  path = require('path');

  log = function() {
    return process.stdout.write(Array.from(arguments).join(' '));
  };

  src = (gitpath) => {
    var config;
    config = fs.readFileSync(path.join(gitpath, 'config'), "utf-8");
    return log(/url\s*=\s*(.*)/.exec(config)[1]);
  };

  (() => {
    var cwd, err, gitpath, st, txt;
    cwd = process.cwd();
    while (true) {
      gitpath = path.join(cwd, '.git');
      cwd = path.dirname(cwd);
      while (true) {
        try {
          st = fs.statSync(gitpath);
        } catch (error) {
          err = error;
          break;
        }
        if (st.isFile()) {
          txt = fs.readFileSync(gitpath, 'utf-8');
          src(path.resolve(path.dirname(gitpath), /gitdir\s*:\s*(.*)/.exec(txt)[1]));
          return;
        } else if (st.isDirectory()) {
          src(gitpath);
          return;
        }
        break;
      }
      if (cwd === "/") {
        break;
      }
    }
    return process.exit();
  })();

}).call(this);
